In [46]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score 

In [8]:
train_data = np.genfromtxt("../dataset/sign_mnist_train.csv",  delimiter=',')
test_data = np.genfromtxt("../dataset/sign_mnist_test.csv",  delimiter=',')

print(train_data.shape)
print(test_data.shape)

(27456, 785)
(7173, 785)
(27455, 785)
(785,)


In [41]:
X_train = train_data[1:,1:]
X_test = test_data[1:,1:]

y_train = train_data[1:,0:1]
y_test = test_data[1:,0:1]

(27455, 784)
(27455, 1)
[[107. 118. 127. ... 204. 203. 202.]
 [155. 157. 156. ... 103. 135. 149.]
 [187. 188. 188. ... 195. 194. 195.]
 ...
 [174. 174. 174. ... 202. 200. 200.]
 [177. 181. 184. ...  64.  87.  93.]
 [179. 180. 180. ... 205. 209. 215.]]


In [40]:
print(y_train)
print(y_test)

[[ 3.]
 [ 6.]
 [ 2.]
 ...
 [18.]
 [17.]
 [23.]]
[[ 6.]
 [ 5.]
 [10.]
 ...
 [ 2.]
 [ 4.]
 [ 2.]]


In [51]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=5, random_state=0)
clf.fit(X_train, y_train.ravel())

RandomForestClassifier(max_depth=5, random_state=0)

In [52]:
print(f1_score(y_test, clf.predict(X_test), average="micro"))

0.47490239821528163


In [55]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train.ravel())

KNeighborsClassifier(n_neighbors=3)

In [56]:
print(f1_score(y_test, neigh.predict(X_test), average="micro"))

0.8039598438371445
